#!/usr/bin/env python3
"""Generate the paper's tables as booktabs .tex fragments.

No number in the paper is hand-typed. Each table here reads a committed
`fc_group/Analysis/*/data/*.csv`, so re-running the analysis pipeline updates the paper and
a reviewer can trace any value back to the script that produced it.

    python fc_group/Analysis/paper/make_tables.py [--out-dir paper]

Writes `tables/t1_paradox.tex` ... `tables/t4_ambiguity.tex`, each a bare `tabular` wrapped
in `table`/`table*` with its own `\\label`, to be `\\input` from the section files.
"""
import argparse
import os
from statistics import stdev

from _common import (ANALYSIS, BASE, BEHAVIOURAL, CHEM, CHEMDFM, COLOR,  # noqa: F401
                     DEFAULT_OUT, FIGURE_LAYER, LABEL, LAYERS, MODELS, R1, REPO, SHORT,
                     fmt, load, num, signed)

HEADER = ('%% GENERATED by fc_group/Analysis/paper/make_tables.py -- do not edit by hand.\n'
          '%% Source: fc_group/Analysis/%s\n')


def write(out_dir, name, source, body):
    path = os.path.join(out_dir, 'tables', name)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as fh:
        fh.write(HEADER % source + body)
    print(f"wrote {os.path.relpath(path, REPO)}")


def t1_paradox(out_dir):
    """Teacher-forced ranking against free generation, with what replaces an answer.

    Every value mirrors that model's `Results/generation_eval/.../summary.json` --
    `raw.accuracy`, `length_normalized.accuracy`, `free_generation.strict_accuracy`,
    `free_generation.superclass_credit_accuracy` and the four adjudication rates -- but is
    read from the committed Analysis CSVs, not from `Results/`, which is gitignored.

    This absorbed the former `t2_free_generation`, which held the commitment columns for the
    three main checkpoints only and was never included by any section. The merge is what the
    numbers ask for: the teacher-forced-to-free drop is not a decoding failure but a
    commitment failure, and that is unreadable unless `commit` and `given commit` sit in the
    same row as the drop they explain. Both log-loss columns were dropped to make room --
    they were the least load-bearing pair (the caption already had to warn they are not
    comparable across the pair) and `log_loss` stays in
    `generation/data/generation_summary.csv` for anyone who wants it.

    Nine numeric columns is the practical ceiling for ICLR single-column text width at
    small type. Keep the tabular spec, the cmidrule spans and the row width in step whenever a
    column moves; they drifted apart once in t3 and the float stopped compiling.
    """
    summ = load('generation/data/generation_summary.csv')
    gen = {r['model']: r for r in summ if r['scoring'] == 'raw'}
    lnorm = {r['model']: r for r in summ if r['scoring'] == 'length_normalized'}
    free = {r['model']: r for r in load('generation/data/free_generation_summary.csv')}
    gdiff = {r['scoring']: r for r in load('generation/data/generation_diff_bootstrap.csv')}
    fdiff = load('generation/data/free_generation_diff_bootstrap.csv')[0]
    # Spread across the 10 prompt templates, read from the released table rather than
    # recomputed here, so the caption's numbers trace to a CSV like every other value.
    sens = {(r['model'], r['scoring']): r
            for r in load('generation/data/template_sensitivity.csv')}

    # LABEL carries a trailing `\textsc{(short)}` gloss that every other table can afford.
    # Here it costs ~80pt in a tabular with no slack, so it is stripped and the caption gives
    # the same mapping in row order instead. Nine numeric columns plus the full labels
    # overflows ICLR's 5.5in text width; this is what buys the fit.
    def short_label(m):
        return LABEL[m].split(r' \textsc{')[0]

    rows = []
    for m in BEHAVIOURAL:
        f = free[m]
        rows.append(' & '.join([
            short_label(m), fmt(gen[m]['accuracy']), fmt(lnorm[m]['accuracy']),
            fmt(f['strict_accuracy']), fmt(sens[(m, 'free_strict')]['sd_accuracy']),
            fmt(f['superclass_credit_accuracy']),
            fmt(f['commit_rate']), fmt(f['conditional_accuracy']),
            fmt(f['malformed_rate']), fmt(f['underspecified_rate']),
            fmt(f['non_answer_rate']),
        ]) + r' \\')

    # Largest teacher-forced-to-strict drop, and whether the two scoring rules rank the
    # models alike. Both found rather than typed, so neither can go stale against the data.
    drop = {m: num(gen[m], 'accuracy') - num(free[m], 'strict_accuracy')
            for m in BEHAVIOURAL}
    worst = max(drop, key=drop.get)
    by_raw = sorted(BEHAVIOURAL, key=lambda m: -num(gen[m], 'accuracy'))
    flip = next(((x, y) for i, x in enumerate(by_raw) for y in by_raw[i + 1:]
                 if num(lnorm[x], 'accuracy') < num(lnorm[y], 'accuracy')), None)
    order_note = (
        r' The rules also disagree on the ordering: \textsc{%s} leads \textsc{%s} on raw '
        r'accuracy and trails it once normalized.' % (SHORT[flip[0]], SHORT[flip[1]])
        if flip else r' The two rules agree on the ordering.')

    # The claim the merge exists to make, computed rather than typed: conditional accuracy
    # is flat across checkpoints while the commit rate is not, so the free-generation spread
    # is commitment and not correctness. If a re-run ever breaks that, the sentence changes
    # with it instead of silently becoming false.
    cond = [num(free[m], 'conditional_accuracy') for m in BEHAVIOURAL]
    commit = [num(free[m], 'commit_rate') for m in BEHAVIOURAL]
    commit_note = (
        r'accuracy \emph{given} a commitment spans only %s--%s across all five checkpoints, '
        r'while the commit rate itself spans %s--%s: the free-generation spread is almost '
        r'entirely whether the model answers, not whether it is right when it does.' % (
            fmt(min(cond)), fmt(max(cond)), fmt(min(commit)), fmt(max(commit))))

    # The containment column is the whole argument for not shipping a containment metric,
    # so it goes in the caption rather than being left for a reader to reconstruct.
    inflation = ', '.join(
        r'%s %s vs %s' % (SHORT[m], fmt(free[m]['containment_accuracy']),
                          fmt(free[m]['strict_accuracy'])) for m in MODELS)
    spread = ', '.join(
        r'%s %s--%s' % (SHORT[m], fmt(sens[(m, 'free_strict')]['min_accuracy']),
                        fmt(sens[(m, 'free_strict')]['max_accuracy'])) for m in BEHAVIOURAL)
    # The SD column cannot be compared down the table on its own: accuracy near 1.0 has
    # nowhere to vary, and across these five models mean accuracy and SD correlate at
    # r = -0.84. The dispersion ratio is the comparable form -- observed SD over the
    # binomial null at that accuracy -- so it goes in the caption rather than leaving a
    # reader to infer the confound. Computed in analyze_generation.py, quoted here.
    # The confound stated as a number, computed rather than typed: if a re-run ever breaks
    # the negative correlation, the caption stops asserting it instead of going quietly stale.
    mus = [num(sens[(m, 'raw')], 'mean_accuracy') for m in BEHAVIOURAL]
    sds = [num(sens[(m, 'raw')], 'sd_accuracy') for m in BEHAVIOURAL]
    mm, ms = sum(mus) / len(mus), sum(sds) / len(sds)
    r_ceiling = (sum((a - mm) * (b - ms) for a, b in zip(mus, sds))
                 / (sum((a - mm) ** 2 for a in mus) * sum((b - ms) ** 2 for b in sds)) ** 0.5)
    disp = '; '.join(
        r'%s %s (t-f) / %s (free)' % (
            SHORT[m], fmt(sens[(m, 'raw')]['dispersion_ratio'], 2),
            fmt(sens[(m, 'free_strict')]['dispersion_ratio'], 2)) for m in BEHAVIOURAL)

    gr = gdiff['raw']
    note = (
        r'\textsc{chem} $-$ \textsc{base}, molecule-level bootstrap (%s draws): '
        r'teacher-forced %s, CI $[%s, %s]$; free generation (strict) %s, CI $[%s, %s]$. '
        r'Both exclude zero, and in the same direction.' % (
            gr['n_boot'], signed(gr['diff_a_minus_b']), signed(gr['ci_lo']).strip('$'),
            signed(gr['ci_hi']).strip('$'), signed(fdiff['diff_a_minus_b']),
            signed(fdiff['ci_lo']).strip('$'), signed(fdiff['ci_hi']).strip('$')))

    body = r"""%% \stack is local to this table: two-line header cells with no extra package.
\providecommand{\stack}[2]{\begin{tabular}[b]{@{}c@{}}#1\\#2\end{tabular}}
\begin{table}[t]
  \centering
  \caption{\textbf{Teacher-forced and free generation on the same prompts, with what
  replaces an answer.} Every column scores the same 920 declarative prompts over 20
  functional-group names (chance $0.05$). \emph{Teacher-forced} never lets the model
  generate: it scores each candidate name as a continuation and takes the argmax. Two
  scoring rules are shown, because ranking by summed log-probability favours short names ---
  \emph{raw} sums the token log-probabilities of a name, \emph{len-norm.}\ divides by its
  token count.%s The remaining columns read the greedy continuation instead, adjudicated on
  what the model commits to rather than on whether the gold string appears.
  \emph{Strict} credits only a single unambiguous class name; \emph{lenient} additionally
  credits naming the family without resolving the member (\texttt{carbonyl} for an ester,
  \texttt{alkyl halide} for a chloride) --- superclass credit, \emph{not} a looser lexicon,
  since both already use the same lenient lexicon in which \texttt{-SH} and ``the bromine
  atom'' count as naming a group. \emph{Commit} is the share of prompts naming any class and
  \emph{given commit} is accuracy among those. The three rightmost columns are disjoint from
  each other and from a commitment: \emph{malformed} is an option enumeration, blank-fill or
  self-retraction, \emph{underspec.}\ names only a superclass, \emph{non-answer} names no
  group at all. The five adjudication outcomes partition the prompts, so \emph{strict} plus
  the three rightmost columns falls short of one by exactly the share that named a group and
  named the wrong one.
  Every model scores lower when it must produce the name than when it need only rank it, and
  the drop is largest for \textsc{%s} ($%s \rightarrow %s$) --- but %s
  Scoring instead by whether the gold name occurs anywhere would read %s, for the three
  checkpoints the rest of the paper analyses; the inflation is almost entirely the base
  model's multiple-choice enumerations, which contain the right word and commit to nothing.
  Both readouts are deterministic --- teacher-forced scoring ranks fixed candidates, decoding
  is greedy --- so \emph{sd (tpl)} --- the standard deviation of
  \emph{strict} across the 10 prompt templates --- is the whole of that column's variance,
  with no sampling variance to add. Ranges of strict accuracy over them: %s. That column is
  \emph{not} comparable down the table on its own: accuracy near $1.0$ has nowhere to vary,
  and across these five checkpoints mean accuracy and this standard deviation correlate at
  $r = %s$. The comparable form divides it by the binomial null $\sqrt{p(1-p)/92}$ --- the
  spread 92 molecules per template would produce at that accuracy even if every template were
  equally good --- giving %s. Every value exceeds $2$, so prompt sensitivity is several times
  sampling noise in \emph{every} model, and it does not order them the way accuracy does. One
  template alone accounts for most of the base model's malformed rate.
  Rows in order are \textsc{base}, \textsc{chem-r}, \textsc{chem}, \textsc{chemdfm} and
  \textsc{reason} --- the short names used throughout the text.
  $^{\dagger}$\textsc{chemdfm} is built on Llama-3 rather than Llama-3.1, so it speaks to
  external validity only --- a \textsc{chemdfm}\,--\,\textsc{base} gap confounds chemistry
  training with the base-model change and is not a controlled contrast; \textsc{chem-r} is
  what carries that. %s}
  \label{tab:paradox}
  \small
  \setlength{\tabcolsep}{3pt}
  \begin{tabular}{lcccccccccc}
    \toprule
    & \multicolumn{2}{c}{Teacher-forced} & \multicolumn{5}{c}{Free generation}
      & \multicolumn{3}{c}{Did not answer} \\
    \cmidrule(lr){2-3}\cmidrule(lr){4-8}\cmidrule(lr){9-11}
    %% Multi-word headers are stacked with inline tabulars (no extra package) because
    %% the header row, not the 0.000 cells, is what sets each column's width here.
    Model & Raw & \stack{Len-}{norm.} & Strict & \stack{sd}{(tpl)} & Lenient & Commit
      & \stack{Given}{commit} & \stack{Mal-}{formed} & \stack{Under-}{spec.}
      & \stack{Non-}{answer} \\
    \midrule
%s
    \bottomrule
  \end{tabular}
\end{table}
""" % (order_note, SHORT[worst], fmt(gen[worst]['accuracy']),
       fmt(free[worst]['strict_accuracy']), commit_note, inflation, spread,
       signed(r_ceiling, 2).strip('$'), disp, note,
       '\n'.join('    ' + r for r in rows))
    write(out_dir, 't1_paradox.tex', 'generation/data/', body)


def t3_geometry(out_dir):
    """Anisotropy and the mean-centered null, for every model with activations.

    Six columns -- model + 2 anisotropy + 3 mean-centered -- and every row emits six. Keep
    the tabular spec and the row width in step whenever a column moves: they drifted apart
    once, the float stopped compiling, and the committed .tex was hand-patched instead,
    which regenerating then kept reverting. Retrieval held two more columns here; it is
    reported in retrieval_by_axis.csv and plotted in the cost and retrieval figures.
    """
    geo = {(r['model'], int(r['layer'])): r
           for r in load('geometry/data/geometry_by_layer.csv')}
    rows = []
    for m in BEHAVIOURAL:
        g = geo[(m, FIGURE_LAYER)]
        rows.append(' & '.join([
            LABEL[m],
            # Inline rather than a seventh column: t3 has no width trouble today and this
            # keeps it that way, and the pairing of a mean with its own spread stays visible.
            r'$%s \pm %s$' % (fmt(g['raw_pairwise_cosine']), fmt(g['raw_pairwise_sd'])),
            fmt(g['diffvec_svd_top1']),
            fmt(g['centered_within']), signed(g['centered_between']),
            signed(g['centered_null']),
        ]) + r' \\')
    body = r"""\begin{table}[t]
  \centering
  \caption{\textbf{What fine-tuning did to the representation} (layer %d). All four
  fine-tunes end less anisotropic than the base, and all four also \emph{widen} the
  distribution: the base model sits at $0.944 \pm 0.018$, about $2\%%$ relative variation over
  all $\binom{92}{2} = 4186$ molecule pairs, so its raw space has almost no dynamic range for
  a cosine to carry chemistry in. The $\pm$ is the descriptive standard deviation of those
  pairs, \emph{not} a standard error --- each molecule appears in 91 of them, so they are not
  independent and it supports no test. Mean-centered \emph{between}-class
  similarity lands on the empirical null in every model, so only \emph{within}-class
  consistency is evidence; the paper's between-class analyses are therefore all relative
  ($z$-scored within a model).
  $^{\dagger}$\textsc{chemdfm} is built on Llama-3 rather than Llama-3.1, so a
  \textsc{chemdfm}\,--\,\textsc{base} gap confounds chemistry training with the base-model
  change and is not a controlled contrast; \textsc{chem-r} is what carries that.}
  \label{tab:geometry}
  \begin{tabular}{lccccc}
    \toprule
    & \multicolumn{2}{c}{Anisotropy} & \multicolumn{3}{c}{Mean-centered cosine} \\
    \cmidrule(lr){2-3}\cmidrule(lr){4-6}
    Model & pairwise (mean $\pm$ sd) & SVD$_1$ & within & between & null \\
    \midrule
%s
    \bottomrule
  \end{tabular}
\end{table}
""" % (FIGURE_LAYER, '\n'.join('    ' + r for r in rows))
    write(out_dir, 't3_geometry.tex', 'geometry/data/', body)


def t4_ambiguity(out_dir):
    """Appendix: the convention-labelled groups, both readings, with best_C on view."""
    amb = [r for r in load('ambiguity/data/ambiguity_two_readings.csv')
           if int(r['layer']) == FIGURE_LAYER]
    by = {(r['model'], r['group']): r for r in amb}
    groups = ['amide', 'nitro', 'sulfone', 'sulfoxide']
    rows = []
    for g in groups:
        cells = [fmt(by[(m, g)]['posterior_delta']) for m in MODELS]
        cells += [signed(by[(m, g)]['geometric_delta'], 2) for m in MODELS]
        rows.append(' & '.join([r'\texttt{%s}' % g] + cells) + r' \\')
    c_note = ', '.join('\\textsc{%s} $%s$' % (
        {BASE: 'base', CHEM: 'chem', R1: 'reason'}[m],
        by[(m, 'amide')]['best_C_mode']) for m in MODELS)
    body = r"""\begin{table}[t]
  \centering
  \caption{\textbf{The convention-labelled groups} (layer %d). Each $\Delta$ is the group's
  lean toward the oxygen family \emph{minus} the lean of its own oxygen-free family
  controls, so a merely diffuse model scores zero. \texttt{amide} leans toward oxygen on
  both readings in all three models --- the durable, within-model result. Cross-model
  ranking is \emph{not} attempted: the two readings disagree (\texttt{nitro} reverses), and
  the modal probe regularization $C$ is matched for \textsc{base}/\textsc{chem} but not
  \textsc{reason}. The sulfur rows are the weak half by design: \texttt{thiol} and
  \texttt{thioether} are themselves the direct analogues of \texttt{alcohol} and
  \texttt{ether}, so the controls sit close to oxygen. Modal probe $C$ over the 19 folds
  at this layer: %s.}
  \label{tab:ambiguity}
  \begin{tabular}{lcccccc}
    \toprule
    & \multicolumn{3}{c}{Posterior $\Delta$} & \multicolumn{3}{c}{Geometric $\Delta$ ($z$)} \\
    \cmidrule(lr){2-4}\cmidrule(lr){5-7}
    Group & base & chem & reason & base & chem & reason \\
    \midrule
%s
    \bottomrule
  \end{tabular}
\end{table}
""" % (FIGURE_LAYER, c_note, '\n'.join('    ' + r for r in rows))
    write(out_dir, 't4_ambiguity.tex', 'ambiguity/data/', body)


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--out-dir', default=DEFAULT_OUT,
                   help='the Overleaf clone (or any dir holding tables/ and figures/)')
    args = p.parse_args()
    for fn in (t1_paradox, t3_geometry, t4_ambiguity):
        fn(args.out_dir)


if __name__ == '__main__':
    main()
