#!/usr/bin/env python3
"""Generate the appendix tables that describe the inputs rather than the results.

    python fc_group/Analysis/paper/make_setup_tables.py [--out-dir paper]

Writes `tables/t5_molecules.tex` (all 92 molecules) and `tables/t6_templates.tex` (all 10
declarative prompt templates), each a `table` float with its own `\\label`, to be `\\input`
from `paper/sections/appendix.tex`.

This is a companion to `make_tables.py`, not part of it. That generator reads only
`fc_group/Analysis/*/data/*.csv`, which is the reproducibility invariant stated in
`_common.py`: a paper table must trace to an analysis output. These two tables trace to the
analysis *inputs* instead -- the dataset CSV and the extraction config -- so they read two
files that `_common.load` deliberately cannot reach. Keeping them in a separate module keeps
that invariant readable rather than qualified.

Nothing here is hand-typed: add a molecule to the dataset or a template to the YAML, re-run,
and the appendix follows.
"""
import argparse
import csv
import os

from _common import DEFAULT_OUT, REPO

DATASET = os.path.join(REPO, 'fc_group', 'functional_group_dataset.csv')
CONFIG = os.path.join(REPO, 'fc_group', 'config_extract_activation.yaml')
# The declarative prompt set the paper measures. The YAML also holds a question-form set and
# two ablations (SMILES-only, IUPAC-only); naming the entity type here rather than taking the
# first block is what keeps this table honest if that file is reordered.
ENTITY_TYPE = 'functional_group'

HEADER = ('%% GENERATED by fc_group/Analysis/paper/make_setup_tables.py -- do not edit by hand.\n'
          '%% Source: %s\n')

# Presentation order: the heteroatom families are the probe's label set, so the table is
# grouped the way Section 3 names them, and within a family the way the dataset lists them.
FAMILIES = [
    ('Hydrocarbon', ['none (alkane)']),
    ('Halide', ['alkyl fluoride', 'alkyl chloride', 'alkyl bromide', 'alkyl iodide']),
    ('Oxygen', ['alcohol', 'ether', 'aldehyde', 'ketone', 'carboxylic acid', 'ester']),
    ('Nitrogen', ['amine', 'imine', 'nitrile', 'amide', 'nitro']),
    ('Sulfur', ['thiol', 'thioether', 'sulfoxide', 'sulfone']),
]
# Where the 92 rows split across two floats. A family boundary, not a row count: the break
# falls after the oxygen block so no family is cut in half.
SPLIT_AFTER = 'Oxygen'

TEX_ESCAPES = {'\\': r'\textbackslash{}', '&': r'\&', '%': r'\%', '$': r'\$',
               '#': r'\#', '_': r'\_', '{': r'\{', '}': r'\}',
               '~': r'\textasciitilde{}', '^': r'\textasciicircum{}'}


def esc(s):
    """LaTeX-safe text. SMILES carry `#` (triple bond) and templates carry `{}` and `_`."""
    return ''.join(TEX_ESCAPES.get(c, c) for c in s)


def write(out_dir, name, source, body):
    path = os.path.join(out_dir, 'tables', name)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as fh:
        fh.write(HEADER % source + body)
    print(f"wrote {os.path.relpath(path, REPO)}")


def load_molecules():
    with open(DATASET) as fh:
        rows = list(csv.DictReader(fh))
    known = {g for _, groups in FAMILIES for g in groups}
    missing = {r['functional_group'] for r in rows} - known
    if missing:
        raise SystemExit(f'dataset holds classes absent from FAMILIES: {sorted(missing)}')
    return rows


def load_templates():
    import yaml
    with open(CONFIG) as fh:
        cfg = yaml.safe_load(fh)
    blocks = [e for e in cfg['extraction']['entities']
              if e['entity_type'] == ENTITY_TYPE]
    if len(blocks) != 1:
        raise SystemExit(f'expected exactly one {ENTITY_TYPE!r} entity block, '
                         f'found {len(blocks)}')
    return blocks[0]['templates']


def molecule_rows(rows):
    """Rows in family order, as (family, [latex row, ...]) so the split can cut cleanly."""
    by_group = {}
    for r in rows:
        by_group.setdefault(r['functional_group'], []).append(r)
    out = []
    for family, groups in FAMILIES:
        lines = []
        for g in groups:
            for r in sorted(by_group[g], key=lambda r: (int(r['carbon_count']),
                                                        r['iupac_name'])):
                lines.append(' & '.join([
                    esc(r['iupac_name']),
                    r'\texttt{%s}' % esc(r['smiles']),
                    r['carbon_count'],
                    r'\texttt{%s}' % esc(r['functional_group']),
                ]) + r' \\')
        out.append((family, lines))
    return out


def tabular(blocks):
    body = []
    for i, (family, lines) in enumerate(blocks):
        if i:
            body.append(r'    \addlinespace[2pt]')
        body.append(r'    \multicolumn{4}{l}{\emph{%s}} \\' % family)
        body.extend('    ' + line for line in lines)
    return r"""  \footnotesize
  \setlength{\tabcolsep}{5pt}
  \begin{tabular}{llcl}
    \toprule
    IUPAC name & SMILES & C & Functional group \\
    \midrule
%s
    \bottomrule
  \end{tabular}""" % '\n'.join(body)


def t5_molecules(out_dir, rows):
    blocks = molecule_rows(rows)
    cut = [f for f, _ in blocks].index(SPLIT_AFTER) + 1
    parts = [blocks[:cut], blocks[cut:]]
    counts = [sum(len(l) for _, l in p) for p in parts]
    total = sum(counts)
    captions = [
        (r'\textbf{The molecule set} (%d of %d). All %d molecules, grouped by the heteroatom '
         r'family the probe targets and, inside a family, by functional-group class '
         r'and chain length. Chain lengths run 3--6 carbons with one molecule per class per '
         r'length, except \texttt{alcohol}, \texttt{amine} and \texttt{thiol}, which carry the '
         r'1- and 2- positional isomers at each length. \texttt{none (alkane)} is the '
         r'unsubstituted backbone each diff vector is taken against. Continued in '
         r'Table~\ref{tab:molecules2}.') % (counts[0], total, total),
        (r'\textbf{The molecule set} (%d of %d), continued from Table~\ref{tab:molecules1}.'
         r' \texttt{amide} and \texttt{nitro} carry oxygen while filed under nitrogen, and '
         r'\texttt{sulfoxide} and \texttt{sulfone} carry oxygen while filed under sulfur; '
         r'those four are the convention-labelled groups of '
         r'Appendix~\ref{app:ambiguity}.') % (counts[1], total),
    ]
    floats = []
    for part, caption, label in zip(parts, captions, ['tab:molecules1', 'tab:molecules2']):
        floats.append(r"""\begin{table}[p]
  \centering
  \caption{%s}
  \label{%s}
%s
\end{table}
""" % (caption, label, tabular(part)))
    write(out_dir, 't5_molecules.tex', 'fc_group/functional_group_dataset.csv',
          '\n'.join(floats))


def t6_templates(out_dir, templates, n_molecules):
    rows = []
    for i, t in enumerate(templates, 1):
        # Templates end mid-sentence with a trailing space, which is the whole point of the
        # design and is invisible in print, so it is stated in the caption instead of being
        # typeset. `\ttfamily` here rather than `\texttt{}` so the p-column can break a long
        # template across lines.
        rows.append(r'    %d & \ttfamily %s \\' % (i, esc(t.rstrip())))
    body = r"""\begin{table}[t]
  \centering
  \caption{\textbf{The ten declarative prompt templates}, verbatim from
  \texttt{config\_extract\_activation.yaml}. Each is instantiated for all %d molecules with
  the IUPAC name and SMILES string of the dataset, giving %d prompts per model. Every
  template ends mid-sentence with a trailing space, so the functional-group name is the
  natural continuation; the trailing space is not shown. The templates vary word order, the
  syntactic slot the molecule occupies and the noun used for the target
  (\emph{group}, \emph{class}, \emph{identity}), while the chemical content is fixed.}
  \label{tab:templates}
  \footnotesize
  \setlength{\tabcolsep}{4pt}
  \begin{tabular}{@{}rp{0.90\linewidth}@{}}
    \toprule
    & Template \\
    \midrule
%s
    \bottomrule
  \end{tabular}
\end{table}
""" % (n_molecules, n_molecules * len(templates), '\n'.join(rows))
    write(out_dir, 't6_templates.tex', 'fc_group/config_extract_activation.yaml', body)


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--out-dir', default=DEFAULT_OUT,
                   help='the Overleaf clone (or any dir holding tables/ and figures/)')
    args = p.parse_args()
    rows = load_molecules()
    t5_molecules(args.out_dir, rows)
    t6_templates(args.out_dir, load_templates(), len(rows))


if __name__ == '__main__':
    main()
