#!/usr/bin/env python3
"""Generate the paper's tables as booktabs .tex fragments.

No number in the paper is hand-typed. Each table here reads a committed
`fc_group/Analysis/*/data/*.csv`, so re-running the analysis pipeline updates the paper and
a reviewer can trace any value back to the script that produced it.

    python fc_group/Analysis/paper/make_tables.py [--out-dir paper]

Writes `tables/t1_paradox.tex` ... `tables/t4_ambiguity.tex`, each a bare `tabular` wrapped
in `table`/`table*` with its own `\\label`, to be `\\input` from the section files.
"""
import argparse
import os
from statistics import stdev

from _common import (ANALYSIS, BASE, CHEM, COLOR, DEFAULT_OUT, FIGURE_LAYER, LABEL,  # noqa: F401
                     LAYERS, MODELS, R1, REPO, SHORT, fmt, load, num, signed)

HEADER = ('%% GENERATED by fc_group/Analysis/paper/make_tables.py -- do not edit by hand.\n'
          '%% Source: fc_group/Analysis/%s\n')


def write(out_dir, name, source, body):
    path = os.path.join(out_dir, 'tables', name)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as fh:
        fh.write(HEADER % source + body)
    print(f"wrote {os.path.relpath(path, REPO)}")


def t1_paradox(out_dir):
    """The centrepiece: behaviour and probe accuracy rank the models oppositely."""
    gen = {r['model']: r for r in load('generation/data/generation_summary.csv')
           if r['scoring'] == 'raw'}
    gdiff = {r['scoring']: r for r in load('generation/data/generation_diff_bootstrap.csv')}
    probe = load('probe/data/layer_curves.csv')
    pdiff = load('probe/data/model_diff_bootstrap.csv')[0]

    best = {}
    for m in MODELS:
        curve = [(int(r['layer']), num(r, 'balanced_acc')) for r in probe
                 if r['model'] == m]
        best[m] = max(curve, key=lambda kv: kv[1])

    rows = []
    for m in MODELS:
        g = gen[m]
        rows.append(' & '.join([
            LABEL[m], fmt(g['accuracy']), fmt(g['balanced_accuracy']),
            fmt(g['log_loss']), fmt(g['mean_top1_margin'], 2),
            fmt(best[m][1]), str(best[m][0]),
        ]) + r' \\')

    gr, pr = gdiff['raw'], pdiff
    note = (
        r'\textsc{chem} $-$ \textsc{base}, molecule-level bootstrap '
        r'(%s draws): generation %s, CI $[%s, %s]$; probe %s, CI $[%s, %s]$. '
        r'Both exclude zero, in opposite directions.' % (
            gr['n_boot'], signed(gr['diff_a_minus_b']), signed(gr['ci_lo']).strip('$'),
            signed(gr['ci_hi']).strip('$'), signed(pr['diff_a_minus_b']),
            signed(pr['ci_lo']).strip('$'), signed(pr['ci_hi']).strip('$')))

    body = r"""\begin{table}[t]
  \centering
  \caption{\textbf{The paradox.} Forced-choice generation over 20 functional-group names
  (920 prompts, chance 0.05) against the layer-wise linear probe on the same categories
  (leave-one-group-out, 5 heteroatom families, chance 0.20). The chemistry-tuned model
  answers far better and probes worse. %s}
  \label{tab:paradox}
  \begin{tabular}{lcccccc}
    \toprule
    & \multicolumn{4}{c}{Generation (20-way)} & \multicolumn{2}{c}{Probe (5-way)} \\
    \cmidrule(lr){2-5}\cmidrule(lr){6-7}
    Model & Acc. & Bal.\ acc. & Log-loss & Margin & Bal.\ acc. & Layer \\
    \midrule
%s
    \bottomrule
  \end{tabular}
\end{table}
""" % (note, '\n'.join('    ' + r for r in rows))
    write(out_dir, 't1_paradox.tex',
          'generation/data/, probe/data/', body)


def t2_free_generation(out_dir):
    """What the models actually emit, once format failures stop counting as answers.

    Table 1's forced choice asks which of 20 names the model ranks highest -- a question it
    can always answer. This asks whether it produces the name unprompted, which the base
    model largely cannot. The two rank the models differently, and differently again from
    the probe, so this is a third ordering rather than a restatement of the first.
    """
    gen = {r['model']: r for r in load('generation/data/free_generation_summary.csv')}
    # Spread across the 10 prompt templates. Greedy decoding is deterministic, so this --
    # not repeated sampling -- is where this readout's variance lives, and it is not evenly
    # shared: the base model's range is nearly twice either fine-tune's.
    tmpl = {}
    for r in load('generation/data/free_generation_by_template.csv'):
        tmpl.setdefault(r['model'], []).append(num(r, 'strict_accuracy'))
    rows = []
    for m in MODELS:
        g = gen[m]
        rows.append(' & '.join([
            LABEL[m], fmt(g['strict_accuracy']), fmt(g['commit_rate']),
            fmt(g['conditional_accuracy']), fmt(g['malformed_rate']),
            fmt(g['underspecified_rate']), fmt(g['non_answer_rate']),
        ]) + r' \\')

    # The containment column is the whole argument for not shipping a containment metric,
    # so it goes in the caption rather than being left for a reader to reconstruct.
    inflation = ', '.join(
        r'%s %s vs %s' % (SHORT[m], fmt(gen[m]['containment_accuracy']),
                          fmt(gen[m]['strict_accuracy'])) for m in MODELS)
    spread = ', '.join(
        r'%s $%s$ (%s--%s)' % (SHORT[m], fmt(stdev(tmpl[m])),
                               fmt(min(tmpl[m])), fmt(max(tmpl[m]))) for m in MODELS)
    body = r"""\begin{table}[t]
  \centering
  \caption{\textbf{Free generation, adjudicated.} Greedy continuations of the same 920
  prompts, scored on what the model commits to rather than on whether the gold string
  appears. \emph{Strict} counts only a single unambiguous class name; \emph{commit} is the
  share of prompts naming any class; \emph{given commit} is accuracy among those.
  The three failure columns are disjoint from each other and from a commitment:
  \emph{malformed} is an option enumeration, blank-fill or self-retraction,
  \emph{underspec.}\ names only a superclass (\texttt{carbonyl}, \texttt{alkyl halide}),
  \emph{non-answer} names no group at all. Scoring instead by whether the gold name occurs
  anywhere would read %s -- the inflation is almost entirely the base model's
  multiple-choice enumerations, which contain the right word and commit to nothing.
  Decoding is greedy and therefore deterministic, so the variation here is across the 10
  prompt templates, not across samples; standard deviation and range of strict accuracy
  over them: %s. The base model is roughly twice as sensitive to phrasing as either
  fine-tune, and one template alone accounts for most of its malformed rate.}
  \label{tab:freegen}
  \begin{tabular}{lcccccc}
    \toprule
    & \multicolumn{3}{c}{Committed answer} & \multicolumn{3}{c}{Did not answer} \\
    \cmidrule(lr){2-4}\cmidrule(lr){5-7}
    Model & Strict & Commit & Given commit & Malformed & Underspec. & Non-answer \\
    \midrule
%s
    \bottomrule
  \end{tabular}
\end{table}
""" % (inflation, spread, '\n'.join('    ' + r for r in rows))
    write(out_dir, 't2_free_generation.tex', 'generation/data/', body)


def t3_geometry(out_dir):
    """Anisotropy, the centered null, and the degenerate-offset cost."""
    geo = {(r['model'], int(r['layer'])): r
           for r in load('geometry/data/geometry_by_layer.csv')}
    rows = []
    for m in MODELS:
        g = geo[(m, FIGURE_LAYER)]
        rows.append(' & '.join([
            LABEL[m], fmt(g['raw_pairwise_cosine']), fmt(g['diffvec_svd_top1']),
            fmt(g['centered_within']), signed(g['centered_between']),
            signed(g['centered_null']), fmt(g['hit1']), fmt(g['degenerate_rate'], 2),
        ]) + r' \\')
    body = r"""\begin{table}[t]
  \centering
  \caption{\textbf{What fine-tuning did to the representation} (layer %d). Both fine-tunes
  end far less anisotropic than the base. Mean-centered \emph{between}-class similarity
  lands on the empirical null in every model, so only \emph{within}-class consistency is
  evidence; the paper's between-class analyses are therefore all relative ($z$-scored
  within a model). The degenerate rate is the share of retrieval trials whose offset never
  leaves the source group's own neighbourhood --- the fine-tuned models match or trail the
  base on hit@1 while failing this check far more often.}
  \label{tab:geometry}
  \begin{tabular}{lcccccc}
    \toprule
    & \multicolumn{2}{c}{Anisotropy} & \multicolumn{3}{c}{Mean-centered cosine}
      & \multicolumn{2}{c}{Retrieval} \\
    \cmidrule(lr){2-3}\cmidrule(lr){4-6}\cmidrule(lr){7-8}
    Model & pairwise & SVD$_1$ & within & between & null & hit@1 & degen. \\
    \midrule
%s
    \bottomrule
  \end{tabular}
\end{table}
""" % (FIGURE_LAYER, '\n'.join('    ' + r for r in rows))
    write(out_dir, 't3_geometry.tex', 'geometry/data/', body)


def t4_ambiguity(out_dir):
    """Appendix: the convention-labelled groups, both readings, with best_C on view."""
    amb = [r for r in load('ambiguity/data/ambiguity_two_readings.csv')
           if int(r['layer']) == FIGURE_LAYER]
    by = {(r['model'], r['group']): r for r in amb}
    groups = ['amide', 'nitro', 'sulfone', 'sulfoxide']
    rows = []
    for g in groups:
        cells = [fmt(by[(m, g)]['posterior_delta']) for m in MODELS]
        cells += [signed(by[(m, g)]['geometric_delta'], 2) for m in MODELS]
        rows.append(' & '.join([r'\texttt{%s}' % g] + cells) + r' \\')
    c_note = ', '.join('\\textsc{%s} $%s$' % (
        {BASE: 'base', CHEM: 'chem', R1: 'reason'}[m],
        by[(m, 'amide')]['best_C_mode']) for m in MODELS)
    body = r"""\begin{table}[t]
  \centering
  \caption{\textbf{The convention-labelled groups} (layer %d). Each $\Delta$ is the group's
  lean toward the oxygen family \emph{minus} the lean of its own oxygen-free family
  controls, so a merely diffuse model scores zero. \texttt{amide} leans toward oxygen on
  both readings in all three models --- the durable, within-model result. Cross-model
  ranking is \emph{not} attempted: the two readings disagree (\texttt{nitro} reverses), and
  the modal probe regularization $C$ is matched for \textsc{base}/\textsc{chem} but not
  \textsc{reason}. The sulfur rows are the weak half by design: \texttt{thiol} and
  \texttt{thioether} are themselves the direct analogues of \texttt{alcohol} and
  \texttt{ether}, so the controls sit close to oxygen. Modal probe $C$ over the 19 folds
  at this layer: %s.}
  \label{tab:ambiguity}
  \begin{tabular}{lcccccc}
    \toprule
    & \multicolumn{3}{c}{Posterior $\Delta$} & \multicolumn{3}{c}{Geometric $\Delta$ ($z$)} \\
    \cmidrule(lr){2-4}\cmidrule(lr){5-7}
    Group & base & chem & reason & base & chem & reason \\
    \midrule
%s
    \bottomrule
  \end{tabular}
\end{table}
""" % (FIGURE_LAYER, c_note, '\n'.join('    ' + r for r in rows))
    write(out_dir, 't4_ambiguity.tex', 'ambiguity/data/', body)


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--out-dir', default=DEFAULT_OUT,
                   help='the Overleaf clone (or any dir holding tables/ and figures/)')
    args = p.parse_args()
    for fn in (t1_paradox, t2_free_generation, t3_geometry, t4_ambiguity):
        fn(args.out_dir)


if __name__ == '__main__':
    main()
